name: vee_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - cupy-cuda11x # Ensure this matches your CUDA version
  - numba
  - llvm-openmp=14 # Pin LLVM version
  - pip
  - pip:
      - opencv-python
